# Generated by Django 3.1.5 on 2021-01-04 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('text', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField(default=0)),
                ('operations', models.CharField(default='', max_length=1000)),
                ('token', models.CharField(default='', max_length=2000, primary_key=True, serialize=False)),
                ('request_approved', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='date signed')),
                ('status', models.CharField(choices=[('NOT DONE', 'Consent has not been signed yet'), ('DONE', 'Consent has been signed')], default='NOT DONE', max_length=8)),
            ],
        ),
    ]
