# Generated by Django 3.1.4 on 2020-12-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genecoop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='chosen_option',
            field=models.IntegerField(default=-1),
        ),
    ]
