"""
Django settings for consent_server project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

from .settingsB import *


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-s02d^&eyk@kfm#@dvab4yp4ii4&!_ip#@nhycir#q^vf#5nb-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


