# Generated by Django 3.1.5 on 2021-01-04 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('key', models.IntegerField(default=0, unique=True)),
                ('chosen_option', models.IntegerField(default=-1)),
                ('chosen_option_text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField(default=0)),
                ('token', models.CharField(default=0, max_length=2000)),
                ('request_sent', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='date sent')),
                ('status', models.CharField(choices=[('NOT SENT', 'Request has not been sent'), ('SENT', 'Request has been sent'), ('NOT REPLIED', 'Request has not been replied'), ('REPLIED', 'Request has been replied')], default='NOT SENT', max_length=15)),
                ('operations', models.ManyToManyField(through='researcher_req.Membership', to='researcher_req.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_req.operation')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_req.operation'),
        ),
        migrations.AddField(
            model_name='membership',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_req.request'),
        ),
    ]
