# Generated by Django 3.1.4 on 2020-12-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_req', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_sent',
            field=models.DateTimeField(default=None, verbose_name='date sent'),
        ),
    ]
