# Generated by Django 3.1.4 on 2020-12-17 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_req', '0002_auto_20201217_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_sent',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='date sent'),
        ),
    ]
