# Generated by Django 3.1.4 on 2020-12-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_req', '0003_auto_20201217_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('NOT SENT', 'Request has not been sent'), ('SENT', 'Request has been sent'), ('REPLIED', 'Request has been fulfilled')], default='NOT SENT', max_length=8),
        ),
    ]
