# Generated by Django 3.1.4 on 2020-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_req', '0004_auto_20201217_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='token',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
